root = "."

[build]
  cmd = "go build -o ./tmp/cmdr ./cmd/cmdr"
  bin = "./tmp/cmdr start -f"
  include_ext = ["go"]
  exclude_dir = ["tmp", "web", "node_modules"]
  delay = 500

[misc]
  clean_on_exit = true
